### ISSUE TITLE
typo ValiadaRequest -> ValidateRequest ?

### ISSUE THREAD

**Issue by cdpb** [faryon93/sackci#10]
https://github.com/faryon93/sackci/blob/5208baf4c31b6a93fcb6b43fb6ca75332fe25ae6/http/session.go#L83
https://github.com/faryon93/sackci/blob/2a34183d613568e41f471c6adc2e861d74ee58de/http/session.go#L83
https://github.com/faryon93/sackci/blob/8f494fc10db00bb0d33fb3f30960646f7a15d98f/rest/project_trigger.go#L202

LG :)

**Comment by faryon93** [comment]
Danke :) werde das gleich nachher fixen :)
